package com.jiuyou.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jiuyou.db.model.Goods;
import com.jiuyou.db.model.Region;
import com.jiuyou.db.model.Category;
import com.jiuyou.db.model.Version;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDaoConfig;
    private final DaoConfig regionDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig versionDaoConfig;

    private final GoodsDao goodsDao;
    private final RegionDao regionDao;
    private final CategoryDao categoryDao;
    private final VersionDao versionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        regionDaoConfig = daoConfigMap.get(RegionDao.class).clone();
        regionDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        versionDaoConfig = daoConfigMap.get(VersionDao.class).clone();
        versionDaoConfig.initIdentityScope(type);

        goodsDao = new GoodsDao(goodsDaoConfig, this);
        regionDao = new RegionDao(regionDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        versionDao = new VersionDao(versionDaoConfig, this);

        registerDao(Goods.class, goodsDao);
        registerDao(Region.class, regionDao);
        registerDao(Category.class, categoryDao);
        registerDao(Version.class, versionDao);
    }
    
    public void clear() {
        goodsDaoConfig.getIdentityScope().clear();
        regionDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        versionDaoConfig.getIdentityScope().clear();
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public RegionDao getRegionDao() {
        return regionDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public VersionDao getVersionDao() {
        return versionDao;
    }

}
