package com.jiuyou.db.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GOODS.
 */
public class Goods {

    private Long id;
    /** Not-null value. */
    private String goodName;
    private Integer goodNum;

    public Goods() {
    }

    public Goods(Long id) {
        this.id = id;
    }

    public Goods(Long id, String goodName, Integer goodNum) {
        this.id = id;
        this.goodName = goodName;
        this.goodNum = goodNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getGoodName() {
        return goodName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    public Integer getGoodNum() {
        return goodNum;
    }

    public void setGoodNum(Integer goodNum) {
        this.goodNum = goodNum;
    }

}
